language: go
go:
- 1.4.3
- 1.5.1
install:
- go get golang.org/x/tools/cmd/cover
- go get -v github.com/axw/gocov/gocov
- go get -v github.com/mattn/goveralls
- go get github.com/codegangsta/cli
- go get github.com/op/go-logging
- go get github.com/stretchr/testify/assert
- go get github.com/goern/grasshopper
script:
- go test -v -covermode=count -coverprofile=profile.cov github.com/goern/grasshopper/nulecule
after_success:
- GOPATH=`pwd`:$GOPATH $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
